spring:
  application:
    name: product-pool-backend

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

  server:
    port: 8080
    servlet:
      context-path: /api

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB
    driverClassName: oracle.jdbc.OracleDriver
    username: testuser
    password: Test123
